#!/usr/bin/expect -f
set timeout 60
spawn ssh -p 65002 -o StrictHostKeyChecking=no u477314974@46.202.172.117
expect {
    -re "password:" {
        send "Tayssir@admin01\r"
        exp_continue
    }
    -re "(%|#|\\$) $" {
        send "cd domains/tayssir-bac.com/public_html/app && echo '{\"app_name\":\"tayssir\",\"version\":\"2.2.0\",\"build_number\":\"44\",\"package_name\":\"tayssir\"}' > version.json\r"
        expect -re "(%|#|\\$) $"
        send "exit\r"
    }
}
