#!/usr/bin/expect -f
set timeout 60
spawn ssh -p 65002 -o StrictHostKeyChecking=no u477314974@46.202.172.117
expect {
    -re "password:" {
        send "Tayssir@admin01\r"
        exp_continue
    }
    -re "(%|#|\\$) $" {
        send "cat domains/tayssir-bac.com/public_html/291013/public/.htaccess\r"
        expect -re "(%|#|\\$) $"
        set output $expect_out(buffer)
        
        send "exit\r"
    }
}
