#!/usr/bin/expect -f
set timeout 120
spawn ssh -p 65002 -o StrictHostKeyChecking=no u477314974@46.202.172.117
expect {
    -re "password:" {
        send "Tayssir@admin01\r"
        exp_continue
    }
    -re "(%|#|\\$) $" {
        send "cd domains/tayssir-bac.com/public_html && rm -rf app app_old\r"
        expect -re "(%|#|\\$) $"
        puts "\nCleaned up app and app_old folders.\n"
        send "exit\r"
    }
}
