// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnMNMlmM1S63QcobQTUbEUP5OFkltAndg',
    databaseURL:
        'https://tayssir-8081a-default-rtdb.europe-west1.firebasedatabase.app/',
    appId: '1:616903115406:web:0316f62d857a074965a0ec', // Placeholder appId, user should provide web appId if needed
    messagingSenderId: '616903115406',
    projectId: 'tayssir-8081a',
    authDomain: 'tayssir-8081a.firebaseapp.com',
    storageBucket: 'tayssir-8081a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnMNMlmM1S63QcobQTUbEUP5OFkltAndg',
    databaseURL:
        'https://tayssir-8081a-default-rtdb.europe-west1.firebasedatabase.app/',
    appId: '1:616903115406:android:76174102c87dd7d4b1bfdf',
    messagingSenderId: '616903115406',
    projectId: 'tayssir-8081a',
    storageBucket: 'tayssir-8081a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnMNMlmM1S63QcobQTUbEUP5OFkltAndg', // Assuming same API key or update manually later
    databaseURL:
        'https://tayssir-8081a-default-rtdb.europe-west1.firebasedatabase.app/',
    appId: '1:616903115406:ios:181dec0990b9fd5c65a0ec', // Placeholder, needs GoogleService-Info.plist
    messagingSenderId: '616903115406',
    projectId: 'tayssir-8081a',
    storageBucket: 'tayssir-8081a.firebasestorage.app',
    iosBundleId: 'com.tayssir.bac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnMNMlmM1S63QcobQTUbEUP5OFkltAndg',
    databaseURL:
        'https://tayssir-8081a-default-rtdb.europe-west1.firebasedatabase.app/',
    appId: '1:616903115406:ios:181dec0990b9fd5c65a0ec',
    messagingSenderId: '616903115406',
    projectId: 'tayssir-8081a',
    storageBucket: 'tayssir-8081a.firebasestorage.app',
    iosBundleId: 'com.tayssir.bac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnMNMlmM1S63QcobQTUbEUP5OFkltAndg',
    databaseURL:
        'https://tayssir-8081a-default-rtdb.europe-west1.firebasedatabase.app/',
    appId: '1:616903115406:web:5e32e7e75ebc920e65a0ec',
    messagingSenderId: '616903115406',
    projectId: 'tayssir-8081a',
    authDomain: 'tayssir-8081a.firebaseapp.com',
    storageBucket: 'tayssir-8081a.firebasestorage.app',
  );
}
